<a href="https://colab.research.google.com/github/raskarrushikesh/Cancer-detection-dataset-with-pandas/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- There are 2 ways to import the dataset in colab:


1.   Using import kagalehub and giving us the path
2.   Using simply uplaod the file in colab and give us path there in colab

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("preetigupta004/cancer-issue")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/preetigupta004/cancer-issue/versions/1

In [ ]:
# Load the dataset into a pandas DataFrame.


import pandas as pd
# Copy path: /content/cancer issue.csv

# Simple way right click on the file and copy the path:

df=pd.read_csv('/content/cancer issue.csv')
df.head()

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South

In [ ]:
# Display the first 10 rows of the dataset.

df.head(10)

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
5,6,64,Female,Asian,33.8,Former Smoker,Yes,Lung,IV,5.2,Combination Therapy,No Response,95,No,NaN,North
6,7,60,Female,Hispanic,26.3,Former Smoker,Yes,Breast,I,5.3,Surgery,Partial Remission,88,No,KRAS,West
7,8,54,Female,African American,25.9,Former Smoker,Yes,Breast,III,10.0,Combination Therapy,Partial Remission,95,No,BRCA1,East
8,9,52,Male,Asian,30.5,Former Smoker,Yes,Leukemia,II,4.7,Surgery,Partial Remission,117,Yes,KRAS,West
9,10,86,Female,Asian,26.7,Non-Smoker,No,Skin,I,5.0,Radiation,Partial Remission,43,Yes,EGFR,South

In [ ]:
# Check for any missing values in the dataset and display the count of missing values per column.

df.isnull().sum()

PatientID               0
Age                     0
Gender                  0
Race/Ethnicity          0
BMI                     0
SmokingStatus           0
FamilyHistory           0
CancerType              0
Stage                   0
TumorSize               0
TreatmentType           0
TreatmentResponse       0
SurvivalMonths          0
Recurrence              0
GeneticMarker        4326
HospitalRegion          0
dtype: int64

In [ ]:
# Check the shape of the DataFrame (number of rows and columns).

df.shape

(17686, 16)

In [ ]:
# Identify the unique values in the column that represents the cancer type.

df.CancerType.unique()

array(['Breast', 'Colon', 'Prostate', 'Lung', 'Leukemia', 'Skin'],
      dtype=object)

In [ ]:
# Find out the column names of the dataset.

df.columns

Index(['PatientID', 'Age', 'Gender', 'Race/Ethnicity', 'BMI', 'SmokingStatus',
       'FamilyHistory', 'CancerType', 'Stage', 'TumorSize', 'TreatmentType',
       'TreatmentResponse', 'SurvivalMonths', 'Recurrence', 'GeneticMarker',
       'HospitalRegion'],
      dtype='object')

In [ ]:
# Get a summary of statistics for the numeric columns in the dataset (using describe).

df.describe().T

,count,mean,std,min,25%,50%,75%,max
PatientID,17686.0,8843.500000,5105.652766,1.0,4422.25,8843.5,13264.75,17686.0
Age,17686.0,53.758396,21.079473,18.0,35.00,54.0,72.00,90.0
BMI,17686.0,29.253805,6.203575,18.5,23.90,29.2,34.60,40.0
TumorSize,17686.0,5.499751,2.603107,1.0,3.30,5.5,7.70,10.0
SurvivalMonths,17686.0,60.387821,34.794859,1.0,30.00,60.0,91.00,120.0

In [ ]:
# informatio of the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17686 entries, 0 to 17685
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PatientID          17686 non-null  int64
 1   Age                17686 non-null  int64
 2   Gender             17686 non-null  object
 3   Race/Ethnicity     17686 non-null  object
 4   BMI                17686 non-null  float64
 5   SmokingStatus      17686 non-null  object
 6   FamilyHistory      17686 non-null  object
 7   CancerType         17686 non-null  object
 8   Stage              17686 non-null  object
 9   TumorSize          17686 non-null  float64
 10  TreatmentType      17686 non-null  object
 11  TreatmentResponse  17686 non-null  object
 12  SurvivalMonths     17686 non-null  int64
 13  Recurrence         17686 non-null  object
 14  GeneticMarker      13360 non-null  object
 15  HospitalRegion     17686 non-null  object
dtypes: float64(2), int64(3), object(11)
memory usage: 2.2+ MB

In [ ]:
# Find the count of occurrences of each cancer type (use value_counts).

df['CancerType'].value_counts()

CancerType
Skin        2980
Leukemia    2957
Lung        2939
Breast      2938
Prostate    2938
Colon       2934
Name: count, dtype: int64

In [ ]:
# Filter the dataset to show only patients over the age of 50.

df[df['Age']> 50]

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17680,17681,57,Female,Other,25.9,Smoker,Yes,Colon,III,1.2,Radiation,Partial Remission,77,No,KRAS,East
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [ ]:
# Sort the dataset by the tumor size in descending order.

# df.groupby('TumorSize').sort_values(by='TumorSize',asceding=False)

df_sorted=df.sort_values(by='TumorSize',ascending=False)
df_sorted.head(10)

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
4840,4841,84,Male,Hispanic,28.4,Smoker,Yes,Breast,III,10.0,Chemotherapy,Partial Remission,81,Yes,EGFR,West
15572,15573,29,Male,Caucasian,34.5,Non-Smoker,Yes,Skin,I,10.0,Combination Therapy,No Response,12,Yes,NaN,East
7862,7863,33,Male,Asian,22.3,Non-Smoker,Yes,Skin,I,10.0,Chemotherapy,No Response,56,No,EGFR,West
4852,4853,61,Male,African American,20.6,Smoker,No,Lung,IV,10.0,Radiation,Partial Remission,22,Yes,BRCA1,North
13840,13841,67,Male,African American,27.6,Non-Smoker,Yes,Breast,IV,10.0,Radiation,Partial Remission,105,Yes,KRAS,South
5118,5119,51,Male,Other,20.1,Former Smoker,Yes,Skin,I,10.0,Chemotherapy,Partial Remission,12,Yes,KRAS,South
15879,15880,58,Female,African American,23.2,Former Smoker,Yes,Leukemia,I,10.0,Radiation,No Response,17,No,NaN,East
753,754,57,Female,Hispanic,30.0,Smoker,No,Skin,III,10.0,Surgery,Complete Remission,84,No,NaN,West
15570,15571,76,Female,Asian,27.6,Non-Smoker,Yes,Skin,I,10.0,Combination Therapy,No Response,31,Yes,EGFR,West
13293,13294,53,Female,Caucasian,22.7,Former Smoker,No,Leukemia,III,10.0,Combination Therapy,Complete Remission,107,No,BRCA1,South

In [ ]:
df['Race/Ethnicity'].unique()

array(['Other', 'Caucasian', 'Asian', 'Hispanic', 'African American'],
      dtype=object)

In [ ]:
# average of age, bmi, tumor_size, survival months

df.loc[:,['Age','BMI','TumorSize','SurvivalMonths']].mean()

Age               53.758396
BMI               29.253805
TumorSize          5.499751
SurvivalMonths    60.387821
dtype: float64

In [ ]:
# Select rows where 'cancer_type' is equal to 'Lung Cancer'

df[df['CancerType']=='Lung']

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
5,6,64,Female,Asian,33.8,Former Smoker,Yes,Lung,IV,5.2,Combination Therapy,No Response,95,No,NaN,North
12,13,51,Female,Hispanic,32.4,Non-Smoker,Yes,Lung,III,4.9,Combination Therapy,No Response,39,Yes,KRAS,South
15,16,63,Male,Other,34.7,Smoker,Yes,Lung,III,4.4,Radiation,Partial Remission,4,Yes,NaN,South
17,18,43,Female,African American,36.4,Non-Smoker,Yes,Lung,I,3.5,Surgery,Partial Remission,9,No,KRAS,North
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17628,17629,57,Female,Other,20.1,Former Smoker,No,Lung,III,3.0,Chemotherapy,No Response,6,No,EGFR,South
17629,17630,60,Male,Other,33.4,Smoker,No,Lung,IV,3.4,Radiation,Partial Remission,43,No,NaN,West
17632,17633,65,Female,Other,25.5,Non-Smoker,No,Lung,III,3.7,Surgery,No Response,79,Yes,NaN,East
17642,17643,61,Male,Caucasian,39.8,Former Smoker,Yes,Lung,IV,2.8,Chemotherapy,No Response,19,Yes,KRAS,West
17657,17658,25,Male,Caucasian,24.0,Former Smoker,No,Lung,IV,1.0,Combination Therapy,Partial Remission,75,Yes,NaN,North

In [ ]:
# Select rows where 'age' is between 30 and 60

# df[df['Age'].between(30,60)]

#other way
df[(df['Age']> 30) & (df['Age']<60)]

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
7,8,54,Female,African American,25.9,Former Smoker,Yes,Breast,III,10.0,Combination Therapy,Partial Remission,95,No,BRCA1,East
8,9,52,Male,Asian,30.5,Former Smoker,Yes,Leukemia,II,4.7,Surgery,Partial Remission,117,Yes,KRAS,West
11,12,48,Male,Asian,35.9,Former Smoker,No,Skin,III,1.7,Surgery,Complete Remission,108,No,NaN,West
12,13,51,Female,Hispanic,32.4,Non-Smoker,Yes,Lung,III,4.9,Combination Therapy,No Response,39,Yes,KRAS,South
13,14,37,Female,African American,29.0,Former Smoker,Yes,Leukemia,IV,3.9,Radiation,No Response,113,Yes,EGFR,East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17667,17668,44,Male,African American,20.3,Smoker,Yes,Leukemia,I,2.6,Chemotherapy,Partial Remission,13,Yes,EGFR,East
17668,17669,36,Female,Other,18.7,Former Smoker,No,Skin,IV,6.0,Radiation,Partial Remission,118,Yes,KRAS,South
17673,17674,53,Female,Asian,29.9,Former Smoker,Yes,Breast,III,3.9,Radiation,Complete Remission,67,No,KRAS,East
17680,17681,57,Female,Other,25.9,Smoker,Yes,Colon,III,1.2,Radiation,Partial Remission,77,No,KRAS,East
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South

In [ ]:
# Select rows where 'tumor_size' is greater than the mean of that column

df['TumorSize'].mean()
# df['TumorSize']>df['TumorSize'].mean()

5.4997512156507975

In [ ]:
df[df['TumorSize']>df['TumorSize'].mean()]

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South
7,8,54,Female,African American,25.9,Former Smoker,Yes,Breast,III,10.0,Combination Therapy,Partial Remission,95,No,BRCA1,East
14,15,57,Female,Hispanic,22.7,Former Smoker,Yes,Leukemia,IV,7.7,Combination Therapy,Complete Remission,42,No,NaN,West
18,19,20,Female,Asian,37.2,Non-Smoker,Yes,Colon,I,9.0,Radiation,Complete Remission,67,Yes,KRAS,East
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17678,17679,86,Male,Asian,35.9,Former Smoker,No,Breast,II,7.9,Combination Therapy,Complete Remission,93,Yes,BRCA1,West
17679,17680,23,Female,Asian,21.7,Smoker,No,Leukemia,III,8.3,Combination Therapy,Complete Remission,38,No,NaN,North
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [ ]:
# Select the first 5 rows and the last 5 rows of the dataset

df.head()

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
0,1,80,Female,Other,23.3,Smoker,Yes,Breast,II,1.7,Combination Therapy,No Response,103,Yes,NaN,South
1,2,76,Male,Caucasian,22.4,Former Smoker,Yes,Colon,IV,4.7,Surgery,No Response,14,Yes,BRCA1,West
2,3,69,Male,Asian,21.5,Smoker,Yes,Breast,III,8.3,Combination Therapy,Complete Remission,61,Yes,BRCA1,West
3,4,77,Male,Asian,30.4,Former Smoker,Yes,Prostate,II,1.7,Radiation,Partial Remission,64,No,KRAS,South
4,5,89,Male,Caucasian,20.9,Smoker,Yes,Lung,IV,7.4,Radiation,No Response,82,Yes,KRAS,South

In [ ]:
df.tail()

,PatientID,Age,Gender,Race/Ethnicity,BMI,SmokingStatus,FamilyHistory,CancerType,Stage,TumorSize,TreatmentType,TreatmentResponse,SurvivalMonths,Recurrence,GeneticMarker,HospitalRegion
17681,17682,48,Male,Caucasian,35.3,Non-Smoker,No,Skin,I,4.9,Radiation,Complete Remission,49,No,EGFR,South
17682,17683,83,Female,Other,32.5,Smoker,No,Breast,I,8.8,Combination Therapy,Partial Remission,61,No,BRCA1,West
17683,17684,86,Male,Caucasian,39.8,Former Smoker,No,Prostate,II,8.6,Chemotherapy,No Response,50,No,NaN,South
17684,17685,77,Female,African American,37.9,Former Smoker,Yes,Prostate,III,1.8,Surgery,No Response,23,No,KRAS,East
17685,17686,80,Female,African American,29.3,Non-Smoker,Yes,Breast,III,9.1,Surgery,Complete Remission,30,No,NaN,East

In [ ]:
# Create a new column as a result of a mathematical operation (e.g., 'age' and 'tumor_size')

df['Age_Tumor']=df['Age'] + df['TumorSize']
df[['Age_Tumor','Age','TumorSize']]

       Age_Tumor  Age  TumorSize
0           81.7   80        1.7
1           80.7   76        4.7
2           77.3   69        8.3
3           78.7   77        1.7
4           96.4   89        7.4
...          ...  ...        ...
17681       52.9   48        4.9
17682       91.8   83        8.8
17683       94.6   86        8.6
17684       78.8   77        1.8
17685       89.1   80        9.1

[17686 rows x 3 columns]

In [ ]:
# Rename 'tumor_size' to 'size_of_tumor'

df.rename(columns={'TumorSize':'Size_of_tumor'},inplace=True)
df.columns

Index(['PatientID', 'Age', 'Gender', 'Race/Ethnicity', 'BMI', 'SmokingStatus',
       'FamilyHistory', 'CancerType', 'Stage', 'Size_of_tumor',
       'TreatmentType', 'TreatmentResponse', 'SurvivalMonths', 'Recurrence',
       'GeneticMarker', 'HospitalRegion', 'new_col', 'Age_Tumor'],
      dtype='object')

In [ ]:
# Create a new DataFrame with 'age' and 'tumor_size', where 'tumor_size' > 5

df_new=df[df['Size_of_tumor']>5] [['Age','Size_of_tumor']]
df_new

       Age  Size_of_tumor
2       69            8.3
4       89            7.4
5       64            5.2
6       60            5.3
7       54           10.0
...    ...            ...
17678   86            7.9
17679   23            8.3
17682   83            8.8
17683   86            8.6
17685   80            9.1

[9745 rows x 2 columns]

In [ ]:
# Group by 'cancer_type' and find the mean, median, and standard deviation of 'tumor_size'

df.groupby('CancerType')['Size_of_tumor'].agg(['mean','median','std']).T

CancerType    Breast     Colon  Leukemia      Lung  Prostate      Skin
mean        5.462219  5.573108  5.496212  5.439367  5.470899  5.556040
median      5.500000  5.600000  5.500000  5.500000  5.400000  5.500000
std         2.607671  2.561961  2.601003  2.645759  2.583940  2.616701

In [ ]:
# Count unique values in 'cancer_type'

df['CancerType'].nunique()

6

In [ ]:
# Group by 'cancer_type' and count occurrences of each group

# df.groupby('CancerType').size()

df['CancerType'].value_counts()

CancerType
Skin        2980
Leukemia    2957
Lung        2939
Breast      2938
Prostate    2938
Colon       2934
Name: count, dtype: int64